# Generated by Django 5.2.8 on 2025-12-04 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.CharField(choices=[('Mom', 'Mom'), ('Dad', 'Dad'), ('Court', 'Court'), ('Andrew', 'Andrew'), ('Ben', 'Ben'), ('Eliza', 'Eliza'), ('Maggie', 'Maggie'), ('Phinney', 'Phinney'), ('Hannah', 'Hannah')], max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type_gift', models.CharField(choices=[('stocking', 'Stocking'), ('main', 'Main')], max_length=20)),
                ('price', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('who', models.ManyToManyField(blank=True, to='main_list.person')),
            ],
        ),
    ]
