# Generated by Django 5.2.8 on 2025-12-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('who', models.CharField(choices=[('Mom', 'Mom'), ('Dad', 'Dad'), ('Court', 'Court'), ('Andrew', 'Andrew'), ('Eliza', 'Eliza'), ('Maggie', 'Maggie'), ('Hannah', 'Hannah')], max_length=50)),
                ('type_gift', models.CharField(choices=[('stocking', 'Stocking'), ('main', 'Main')], max_length=20)),
                ('price', models.FloatField()),
            ],
        ),
    ]
