# Generated by Django 5.2.8 on 2025-12-02 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.CharField(choices=[('Mom', 'Mom'), ('Dad', 'Dad'), ('Court', 'Court'), ('Andrew', 'Andrew'), ('Eliza', 'Eliza'), ('Maggie', 'Maggie'), ('Hannah', 'Hannah')], max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='who',
        ),
        migrations.AddField(
            model_name='item',
            name='who',
            field=models.ManyToManyField(blank=True, to='main_list.person'),
        ),
    ]
