# Generated by Django 5.2.8 on 2025-12-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='year',
            field=models.IntegerField(default=2025),
        ),
    ]
