# Generated by Django 5.2.8 on 2025-12-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_list', '0002_create_people_for_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='who',
            field=models.CharField(choices=[('Mom', 'Mom'), ('Dad', 'Dad'), ('Court', 'Court'), ('Andrew', 'Andrew'), ('Ben', 'Ben'), ('Eliza', 'Eliza'), ('Maggie', 'Maggie'), ('Phinney', 'Phinney'), ('Secret santa', 'Secret santa')], max_length=200),
        ),
    ]
