# Generated by Django 5.2.8 on 2025-12-02 03:45

from django.db import migrations

def create_people(apps, schema_editor):
    Person = apps.get_model("main_list", "Person")
    people = ['Mom', 'Dad', 'Court', 'Andrew', 'Eliza', 'Maggie', 'Hannah']
    for who in people:
        Person.objects.get_or_create(who=who)

class Migration(migrations.Migration):

    dependencies = [
        ('main_list', '0002_person_remove_item_who_item_who'),
    ]

    operations = [
        migrations.RunPython(create_people)
    ]
